; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL	86400
@	IN	SOA	anjana.ajresource.com. root.localhost. (
			      1		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	localhost.
	IN	A	10.108.40.101	
ubu01	IN 	A	10.108.40.101
ubu02	IN	A	10.108.40.102
ubu03	IN	A	10.108.40.103
